name: cppcheck-action
on: [push]

jobs:
  build:
    name: cppcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: cppcheck
        uses: deep5050/cppcheck-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          check_library: disable
          skip_preprocessor: disable
          enable: all
          exclude_check: ./build
          inconclusive: enable
          inline_suppression: disable
          force_language: c++
          force: disable
          max_ctu_depth: 2
          platform: unspecified
          std: c++17
          output_file: ./cppcheck_report.txt
          other_options: disable

      - name: publish report    
        uses: mikeal/publish-to-github-action@master
      
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          name: cpplog
          path: ./cppcheck_report.txt
          retention-days: 5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: 'main' # your branch name goes here
